<?xml version="1.0"?>
<?xml-stylesheet type='text/xsl' href='xLogResultError.xslt'?>
<!--Log de errores (Sistema: A2Utilidades.Utilitarios)-->
<xml>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>10:55:57.477</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>CF_MaestrosDataContext</Modulo>
    <Funcion>SubmitChanges</Funcion>
    <Tipo>Exception</Tipo>
    <Mensaje>Ya existe la calificación inversión. No se puede grabar el registro </Mensaje>
    <Detalle>System.Exception: Ya existe la calificación inversión. No se puede grabar el registro  ---&gt; System.Exception: validacionA2
   --- End of inner exception stack trace ---
   at System.Data.Linq.ChangeDirector.StandardChangeDirector.Insert(TrackedObject item)
   at System.Data.Linq.ChangeProcessor.SubmitChanges(ConflictMode failureMode)
   at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
   at A2.OyD.OYDServer.RIA.Web.CF_MaestrosDataContext.SubmitChanges(ConflictMode failureMode) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\CF_Maestros.vb:line 23</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>10:56:5.896</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>CF_MaestrosDataContext</Modulo>
    <Funcion>SubmitChanges</Funcion>
    <Tipo>Exception</Tipo>
    <Mensaje>Ya existe la calificación inversión. No se puede grabar el registro </Mensaje>
    <Detalle>System.Exception: Ya existe la calificación inversión. No se puede grabar el registro  ---&gt; System.Exception: validacionA2
   --- End of inner exception stack trace ---
   at System.Data.Linq.ChangeDirector.StandardChangeDirector.Insert(TrackedObject item)
   at System.Data.Linq.ChangeProcessor.SubmitChanges(ConflictMode failureMode)
   at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
   at A2.OyD.OYDServer.RIA.Web.CF_MaestrosDataContext.SubmitChanges(ConflictMode failureMode) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\CF_Maestros.vb:line 23</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:6:55.523</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.MaestrosCFDomainService</Modulo>
    <Funcion>Traer_Departamentos_Paise</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   at System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.CF_MaestrosDataContext.uspOyDNet_Maestros_DepartamentosPaise_Consultar(Int32 pintIDPais, String infosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\CF_Maestros.designer.vb:line 550
   at A2.OyD.OYDServer.RIA.Web.MaestrosCFDomainService.Traer_Departamentos_Paise(Int32 pIDPais, String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\MaestrosCFDomainService.vb:line 975
ClientConnectionId:0020273a-f126-42d2-9150-ae2c8c570491
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:9:56.452</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>CF_MaestrosDataContext</Modulo>
    <Funcion>SubmitChanges</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
   at A2.OyD.OYDServer.RIA.Web.CF_MaestrosDataContext.SubmitChanges(ConflictMode failureMode) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\CF_Maestros.vb:line 23
ClientConnectionId:b914a1ae-6d1c-4c14-8a2e-3dc4148debfc
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:12:51.191</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>CF_MaestrosDataContext</Modulo>
    <Funcion>SubmitChanges</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.DataContext.SubmitChanges(ConflictMode failureMode)
   at A2.OyD.OYDServer.RIA.Web.CF_MaestrosDataContext.SubmitChanges(ConflictMode failureMode) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\CF\A2.CF.RIA.Maestros.Web\CF_Maestros.vb:line 23
ClientConnectionId:49cdf940-3520-4970-aac1-37accffeac02
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:15:4.81</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.UtilidadesDomainService</Modulo>
    <Funcion>Verificaparametro</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   at System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OYDUtilidadesDataContext.usp_Validaparametro_OyDNet(String pstrParametro, String&amp; strvalor) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\GEN\A2.OyD.OYDServer.RIA.Utilidades.Web\OYD_Utilidades.designer.vb:line 526
   at A2.OyD.OYDServer.RIA.Web.UtilidadesDomainService.Verificaparametro(String strparametro, String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\GEN\A2.OyD.OYDServer.RIA.Utilidades.Web\UtilidadesDomainService.vb:line 266
ClientConnectionId:2d5a61ce-7870-479f-a83c-2bfa0f903300
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:38:44.410</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService</Modulo>
    <Funcion>TipoNegocioFiltrar</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   at System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDataContext.uspOyDNet_Maestros_TipoNegocio_Filtrar(String pstrFiltro, String pstrUsuario, String pstrInfosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUS_Maestros.designer.vb:line 895
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService.TipoNegocioFiltrar(String pstrFiltro, String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUSMaestrosDomainService.vb:line 455
ClientConnectionId:eff79327-99a3-4181-9f72-d7b3861a02c1
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:39:32.864</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService</Modulo>
    <Funcion>TipoNegocioFiltrar</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   at System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   at System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDataContext.uspOyDNet_Maestros_TipoNegocio_Filtrar(String pstrFiltro, String pstrUsuario, String pstrInfosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUS_Maestros.designer.vb:line 895
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService.TipoNegocioFiltrar(String pstrFiltro, String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUSMaestrosDomainService.vb:line 455
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:-1,State:0,Class:20</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:40:25.259</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService</Modulo>
    <Funcion>RN_TiposDocumentoConsultar</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
   at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDataContext.uspOyDNet_Maestros_RN_TiposDocumento_Consultar(String pstrUsuario, String pstrInfosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUS_Maestros.designer.vb:line 1152
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService.RN_TiposDocumentoConsultar(String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUSMaestrosDomainService.vb:line 1413
ClientConnectionId:e2cc1c26-993f-4ff1-ad19-58fbdaa09b55
Error Number:50000,State:0,Class:16</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:40:25.477</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService</Modulo>
    <Funcion>RN_ConfiguracionNivelAtribucionFiltrar</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
   at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDataContext.uspOyDNet_Maestros_RN_ConfiguracionNivelAtribucion_Filtrar(String pstrFiltro, String pstrUsuario, String pstrInfosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUS_Maestros.designer.vb:line 1146
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService.RN_ConfiguracionNivelAtribucionFiltrar(String pstrFiltro, String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUSMaestrosDomainService.vb:line 1338
ClientConnectionId:65136a1b-a63b-4b67-8984-ad648983fa27
Error Number:50000,State:0,Class:16</Detalle>
  </Log>
  <Log>
    <Fecha>2018/08/08</Fecha>
    <Hora>15:40:35.896</Hora>
    <Usuario>
    </Usuario>
    <Sistema>A2Utilidades.Utilitarios</Sistema>
    <Version>1.0.0.1</Version>
    <Modulo>A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService</Modulo>
    <Funcion>RN_NivelesAtribucionConsultar</Funcion>
    <Tipo>SqlException</Tipo>
    <Mensaje>A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.</Mensaje>
    <Detalle>System.Data.SqlClient.SqlException (0x80131904): A .NET Framework error occurred during execution of user-defined routine or aggregate "ufnAutorizacion_ConsultarSistemas": 
System.IO.FileLoadException: Could not load file or assembly 'System.ServiceModel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Assembly in host store has a different signature than assembly in GAC. (Exception from HRESULT: 0x80131050) See Microsoft Knowledge Base article 949080 for more information.
System.IO.FileLoadException: 
   at A2.Autorizaciones.ObjetoServicioAutorizaciones.clsObjetoServicioAutorizaciones.ufnAutorizacion_ConsultarSistemas(SqlString pstrUrlServicio, SqlString pstrNombre, SqlBoolean plogHacerLog, SqlString pstrRutaLog)
.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean&amp; usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)
   at System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)
   at System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDataContext.uspOyDNet_Maestros_RN_NivelesAtribucion_Consultar(String pstrUsuario, String pstrInfosesion, Nullable`1 pintErrorPersonalizado) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUS_Maestros.designer.vb:line 1158
   at A2.OyD.OYDServer.RIA.Web.OyDPLUSMaestrosDomainService.RN_NivelesAtribucionConsultar(String pstrUsuario, String pstrInfoConexion) in E:\DLLO\WPF\Versiones\Desarrollo\Fuentes\PLUS\A2.OyD.OYDServer.RIA.PLUSMaestros.Web\OyDPLUSMaestrosDomainService.vb:line 1424
ClientConnectionId:a96e3677-a3a2-4232-9164-251ab3c82a33
Error Number:50000,State:0,Class:16</Detalle>
  </Log>
</xml>